name: Release

# listen on tag with name like v1.0.0
on:
  create:
    branch:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - name: Checking if the related commit has passed the Soaking test
        run: echo "Checking Soaking test"

      - name: Download the release artifact base on the commit hash
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: integ-test.yml
          commit: ${{ github.sha }}
          name: packages_artifact
          path: build/packages

      - name: Configure AWS Credentials, TODO change to the release account credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
          aws-region: us-west-2

      - name: Release to S3
        uses: wyTrivail/aocintegtest@master
        with:
          task: S3Release
          stack: release
